### ISSUE TITLE
Cannot Compile Container Definitions to File in Production Environment

### ISSUE THREAD

**Issue by Noctis** [Noctis/kickstart-app#43]
When trying to run a freshly created Kickstart 3.0.0 project, the following error can be seen in browser:

```
Fatal error: Uncaught DI\Definition\Exception\InvalidDefinition: Cannot compile closures which use $this or self/static/parent references in .../vendor/php-di/php-di/src/Compiler/Compiler.php:412 
Stack trace: 
#0 .../vendor/php-di/php-di/src/Compiler/Compiler.php(353): DI\Compiler\Compiler->compileClosure(Object(Closure)) 
#1 .../vendor/php-di/php-di/src/Compiler/Compiler.php(307): DI\Compiler\Compiler->compileValue(Object(Closure)) 
#2 .../vendor/php-di/php-di/src/Compiler/Compiler.php(160): DI\Compiler\Compiler->compileDefinition('Noctis\\KickStar...', Object(DI\Definition\FactoryDefinition)) 
#3 .../vendor/php-di/php-di/src/ContainerBuilder.php(182): DI\Compiler\Compiler->compile(Object(DI\Definition\Source\SourceChain), '/var/www/kickst...', 'CompiledContain...', 'DI\\CompiledCont...', true) 
#4 .../vendor/noctis/kickstart/src/AbstractContainerBuilder.php(66): DI\ContainerBuilder->build() 
#5 .../public/index.php(32): Noctis\KickStart\AbstractContainerBuilder->build() 
#6 {main} thrown in .../vendor/php-di/php-di/src/Compiler/Compiler.php on line 412
```

The error goes away when compiling container definitions is disabled, ie. by setting `APP_ENV=dev` in `.env`.

**Comment by Noctis** [comment]
Problem lies in the `Noctis\KickStart\Provider\RoutingProvider` class: https://github.com/Noctis/kickstart/blob/3.0.0/src/Provider/RoutingProvider.php#L38

**Comment by Noctis** [comment]
Looks like I didn't [RTFM](https://php-di.org/doc/performances.html#optimizing-for-compilation) when I enabled container definitions compilation by default in a production environment.
